# Generated by Django 3.1.2 on 2020-10-18 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'exercise_type',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('program_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=45)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.program')),
            ],
            options={
                'db_table': 'program_day',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'unit_type',
            },
        ),
        migrations.CreateModel(
            name='WAUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('complete', models.IntegerField(blank=True, null=True)),
                ('expected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.wauser')),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seq_num', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.wauser')),
                ('weight_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.unittype')),
            ],
            options={
                'db_table': 'user_weight',
            },
        ),
        migrations.CreateModel(
            name='UserSheet',
            fields=[
                ('user_sheet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sheet_id', models.CharField(blank=True, max_length=45, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.wauser')),
            ],
            options={
                'db_table': 'user_sheet',
            },
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('user_program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.wauser')),
            ],
            options={
                'db_table': 'user_program',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.wauser')),
            ],
            options={
                'db_table': 'user_model',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=10)),
                ('rpe', models.DecimalField(decimal_places=0, max_digits=10)),
                ('set_number', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.exercisetype')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.unittype')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.workout')),
            ],
            options={
                'db_table': 'set',
            },
        ),
        migrations.CreateModel(
            name='ExpectedSet',
            fields=[
                ('exp_set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_num', models.IntegerField()),
                ('reps_min', models.IntegerField()),
                ('rpe', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reps_max', models.IntegerField(blank=True, null=True)),
                ('amrap', models.IntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.programday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkoutAppWebGUI.exercisetype')),
            ],
            options={
                'db_table': 'expected_set',
            },
        ),
    ]
