# Generated by Django 3.1.2 on 2020-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0002_auto_20201018_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersheet',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='user_program_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='UserSheet',
        ),
    ]
