# Generated by Django 3.1.2 on 2020-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0003_auto_20201026_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedset',
            name='amrap',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
