# Generated by Django 3.1.2 on 2020-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0004_auto_20201030_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedset',
            name='amrap',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
