# Generated by Django 3.1.2 on 2021-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0005_auto_20201030_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='weight_step',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='weighted',
            field=models.BooleanField(default=True),
        ),
    ]
