# Generated by Django 3.1.2 on 2021-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0007_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='user_agrees',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='user_suggestion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='prediction',
            table='prediction',
        ),
    ]
