# Generated by Django 3.1.2 on 2021-08-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0008_auto_20210813_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutAppWebGUI.workout'),
        ),
    ]
