# Generated by Django 3.1.2 on 2021-08-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutAppWebGUI', '0009_auto_20210814_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutAppWebGUI.workout'),
        ),
    ]
